export const TYPERACER_ABI = [
  {
    type: "impl",
    name: "TypeRacerImpl",
    interface_name: "typeracer::ITypeRacer",
  },
  {
    type: "enum",
    name: "core::bool",
    variants: [
      { name: "False", type: "()" },
      { name: "True", type: "()" },
    ],
  },
  {
    type: "struct",
    name: "typeracer::RaceInfo",
    members: [
      { name: "racer", type: "core::starknet::contract_address::ContractAddress" },
      { name: "challenge_id", type: "core::integer::u32" },
      { name: "keystroke_count", type: "core::integer::u32" },
      { name: "start_time", type: "core::integer::u64" },
      { name: "end_time", type: "core::integer::u64" },
      { name: "wpm", type: "core::integer::u32" },
      { name: "accuracy", type: "core::integer::u32" },
      { name: "finished", type: "core::bool" },
    ],
  },
  {
    type: "interface",
    name: "typeracer::ITypeRacer",
    items: [
      {
        type: "function",
        name: "start_race",
        inputs: [{ name: "challenge_id", type: "core::integer::u32" }],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "record_keystroke",
        inputs: [{ name: "race_id", type: "core::integer::u64" }],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "finish_race",
        inputs: [
          { name: "race_id", type: "core::integer::u64" },
          { name: "correct_chars", type: "core::integer::u32" },
          { name: "total_chars", type: "core::integer::u32" },
          { name: "wpm", type: "core::integer::u32" },
          { name: "accuracy", type: "core::integer::u32" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_race",
        inputs: [{ name: "race_id", type: "core::integer::u64" }],
        outputs: [{ type: "typeracer::RaceInfo" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_user_best_wpm",
        inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
        outputs: [{ type: "core::integer::u32" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_user_race_count",
        inputs: [{ name: "user", type: "core::starknet::contract_address::ContractAddress" }],
        outputs: [{ type: "core::integer::u32" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_total_races",
        inputs: [],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_total_keystrokes",
        inputs: [],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "view",
      },
    ],
  },
  { type: "constructor", name: "constructor", inputs: [] },
  {
    type: "event",
    name: "typeracer::TypeRacerContract::RaceStarted",
    kind: "struct",
    members: [
      { name: "racer", type: "core::starknet::contract_address::ContractAddress", kind: "key" },
      { name: "race_id", type: "core::integer::u64", kind: "data" },
      { name: "challenge_id", type: "core::integer::u32", kind: "data" },
      { name: "timestamp", type: "core::integer::u64", kind: "data" },
    ],
  },
  {
    type: "event",
    name: "typeracer::TypeRacerContract::Keystroke",
    kind: "struct",
    members: [
      { name: "racer", type: "core::starknet::contract_address::ContractAddress", kind: "key" },
      { name: "race_id", type: "core::integer::u64", kind: "data" },
      { name: "keystroke_number", type: "core::integer::u32", kind: "data" },
      { name: "timestamp", type: "core::integer::u64", kind: "data" },
    ],
  },
  {
    type: "event",
    name: "typeracer::TypeRacerContract::RaceFinished",
    kind: "struct",
    members: [
      { name: "racer", type: "core::starknet::contract_address::ContractAddress", kind: "key" },
      { name: "race_id", type: "core::integer::u64", kind: "data" },
      { name: "wpm", type: "core::integer::u32", kind: "data" },
      { name: "accuracy", type: "core::integer::u32", kind: "data" },
      { name: "keystroke_count", type: "core::integer::u32", kind: "data" },
      { name: "elapsed_seconds", type: "core::integer::u64", kind: "data" },
    ],
  },
  {
    type: "event",
    name: "typeracer::TypeRacerContract::Event",
    kind: "enum",
    variants: [
      { name: "RaceStarted", type: "typeracer::TypeRacerContract::RaceStarted", kind: "nested" },
      { name: "Keystroke", type: "typeracer::TypeRacerContract::Keystroke", kind: "nested" },
      { name: "RaceFinished", type: "typeracer::TypeRacerContract::RaceFinished", kind: "nested" },
    ],
  },
] as const;
